Category average costs
Crunch-Dandies/budget-planner pull request #9
Opened 2023-07-08 12:01 UTC by souldrum

2023-07-08 12:27 UTC, kib357 requested changes

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/OperationsRatio.tsx
> -    <div className="split text-label-sm md:text-title text-on-surface-variant">
Надо проверить, убрать трэкинг. По трэкингу, если нужно, надо добавить в index.css для всех лейблов

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/CategoryAnalytics.tsx
> +  const { currentSpent, noStats } = useDataForExpenseHistory(
useExpenseAnalytics

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/CategoryAnalytics.tsx
> +    <div className="my-6 min-h-[94px] overflow-hidden overflow-x-auto rounded-xl">
попробовать поменять min-h на padding bottom

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +        <InformationCircleIcon className="h-[18px]" />
h-[18px] поменять на h-5

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +    <div className="flex h-full w-full min-w-full flex-col rounded-xl border border-outline bg-error-container py-2 px-3 text-on-error-container">
Попробовать убрать "flex h-full w-full min-w-full flex-col"

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +      <div className="flex items-center text-on-error-container">
text-on-error-container задублирован

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +        <span className="text-label">&nbsp;Ошибка статистики по периодам:</span>
Заменить `&nbsp;` на gap в родительском контейнере

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/useDataForExpenseHistory.ts
> +    const { getSpentAmount } = useExpense(expenseId);
Нельзя запускать хуки внутри условий, нужно убрать if

2023-07-08 12:27 UTC, kib357 commented on frontend/src/budget/expense/analytics/useDataForExpenseHistory.ts
> +  let currentSpent: number | undefined;
Нужно вынести currentSpent из этого хука, например, в отдельный хук useExpenseSpentAmount или использовать сразу на уровне компонента

2023-07-09 06:20 UTC, souldrum commented on frontend/src/budget/OperationsRatio.tsx
> -    <div className="split text-label-sm md:text-title text-on-surface-variant">
1. Трэкинг убрал. В лэйблы, думаю, добавлять не нужно, иначе то, что терпимо под ratio, будет не очень красиво в остальных местах.
2. md:text-title проверил, убрал обосновано, поскольку иначе "остаток" и "потрачено" становятся очень крупными, что не соответствует и дизайну в фигме, и чисто эстетически не логично. Раньше, когда ratio было без карточки на всю ширину блока операции — было логично, поскольку и полоса ratio была крупнее

2023-07-09 06:29 UTC, souldrum commented on frontend/src/budget/expense/analytics/CategoryAnalytics.tsx
> +  const { currentSpent, noStats } = useDataForExpenseHistory(
Переименовал

2023-07-09 06:46 UTC, souldrum commented on frontend/src/budget/expense/analytics/useDataForExpenseHistory.ts
> +    const { getSpentAmount } = useExpense(expenseId);
Убрал этот блок полностью. Для получения необходимого значения сделал отдельный маленький хук useExpenseSpentAmount

2023-07-09 06:46 UTC, souldrum commented on frontend/src/budget/expense/analytics/useDataForExpenseHistory.ts
> +  let currentSpent: number | undefined;
Убрал этот блок полностью. Для получения необходимого значения сделал отдельный маленький хук useExpenseSpentAmount

2023-07-09 07:01 UTC, souldrum commented on frontend/src/budget/expense/analytics/CategoryAnalytics.tsx
> +    <div className="my-6 min-h-[94px] overflow-hidden overflow-x-auto rounded-xl">
Поменял, всё работает (не помню, почему до этого сопротивлялось, но пробовал и раньше). Так же сделал этот паддинг динамическим. В зависимости от количества карточек в категории (нужен скролл, или нет) переменная scrollSpace добавляет/не добавляет паддинг. Не понравится – уберу)

2023-07-09 07:11 UTC, souldrum commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +        <InformationCircleIcon className="h-[18px]" />
Поменял

2023-07-09 07:11 UTC, souldrum commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +        <span className="text-label">&nbsp;Ошибка статистики по периодам:</span>
заменил

2023-07-09 07:18 UTC, souldrum commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +    <div className="flex h-full w-full min-w-full flex-col rounded-xl border border-outline bg-error-container py-2 px-3 text-on-error-container">
Получилось без потерь убрать только w-full, если убирать остальные – всё ползет/плывет. При текущей реализации по-другому никак. Либо всё по новой переверстывать

2023-07-09 07:23 UTC, souldrum commented on frontend/src/budget/expense/analytics/ExpenseHistoryError.tsx
> +      <div className="flex items-center text-on-error-container">
Убрал дублирование в дочернем, чтоб цвет распространялся на весь текст (по крайней мере такая задумка была)

2023-07-09 09:09 UTC, kib357 requested changes

2023-07-09 09:09 UTC, kib357 commented on frontend/src/budget/expense/analytics/useExpenseAnalytics.ts
> +      setAverageSpent(Amount.create(average.spent).unwrap());
Установка средних значений задублирована и не хватает проверки на их наличие

2023-07-09 10:31 UTC, souldrum commented on frontend/src/budget/expense/analytics/useExpenseAnalytics.ts
> +      setAverageSpent(Amount.create(average.spent).unwrap());
Поправил

2023-07-09 14:28 UTC, kib357 approved these changes

2023-07-09 15:41 UTC, merged